<?php
namespace app\controllers;


use app\m\News;
use yii\rest\ActiveController;
use yii\web\Controller;
use yii\web\Response;

class UserController extends  ActiveController
{
    public $modelClass = 'app\m\Users';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }

    public function init(){

        $this->enableCsrfValidation = false;
    }

    /* function actions()
     {
         $action= parent::actions(); // TODO: Change the autogenerated stub
         unset($action["index"]);
     }

     public  function actionIndex()
     {
         echo "shenyi";
     }*/
    function actionDo()
    {
        $news=new News();

        echo $news::find()->count();

    }
}